# Generated by Django 5.0.2 on 2024-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.FloatField(verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='working_ver',
            field=models.BooleanField(blank=True, null=True, verbose_name='Признак версии'),
        ),
    ]
